### PR TITLE
Change rpc import lines to match new directory

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Finally getting around to prepping PRs for vendoring https://github.com/keybase/go-framed-msgpack-rpc/pull/100 .

**Comment by maxtaco** [comment]
Please change `emit.iced` and then generate `emit.js` via `npm i && make`

**Comment by akalin-keybase** [comment]
Done, PTAL!

**Comment by maxtaco** [comment]
Thanks for the fix.  Will this break with the current library though?

**Comment by akalin-keybase** [comment]
I'm prepping all the PRs to vendor https://github.com/keybase/go-framed-msgpack-rpc/pull/100 and will check them all roughly at the same time. That should work, right?

**Comment by maxtaco** [comment]
Yes but in this case, I need to make a push to npm.

**Comment by akalin-keybase** [comment]
Okay, so maybe after I push all the vendoring PRs, you can push to npm?

**Comment by maxtaco** [comment]
ok! we peg to a version #, so no worries if we push to npm ahead of when we refer to the new version.

**Comment by maxtaco** [comment]
👍

**Comment by akalin-keybase** [comment]
Actually, it looks like from https://ci.keybase.io/job/client/job/PR-4477/1/execution/node/112/log/ that we should commit this, push to npm, then all the other vendoring PRs could bump the pegged version.

**Comment by maxtaco** [comment]
Ok, we just have to remember not to add any other features in the mean time

**Comment by akalin-keybase** [comment]
OK, ready to push to npm!

**Pull request merged**
