### PR TITLE
variants shouldn't force nulls

### PR DESCRIPTION
**Pull request by chrisnojima**
cc: @malgorithms

### CODE REVIEW

**Comment by mlsteele** [comment]
Does this come with a change to serialization in Go?

Here's an example of an empty list (according to avdl) being serialized as `null` in json by the service. The `commands` field.

```
  record ListCommandsRes {
    @jsonkey("commands")
    array<UserBotCommandOutput> commands;
    @jsonkey("ratelimits")
    @optional(true)
    array<RateLimitRes> rateLimits;
  }
```

```
$ keybase-prod chat api -m '{"method": "listcommands", "params": {"options": {"channel": {"name": "mikem"}}}}'
{"result":{"commands":null,"ratelimits":[{"tank":"chat","capacity":9000,"reset":617,"gas":8982}]}}
```

**Comment by chrisnojima** [comment]
Is that a variant

**Comment by mlsteele** [comment]
Nope, I misread.

**Comment by chrisnojima** [comment]
@mlsteele maybe you can help here. my local tests fail due to this relative path change. see https://github.com/keybase/node-avdl-compiler/pull/31/files

**Comment by chrisnojima** [comment]
- [x] upped version
- [x] tested against client

**Pull request merged**
